### ISSUE TITLE
Cannot run with node once compiled

### ISSUE THREAD

**Issue by DevFlex** [fullstack-build/tslog#33]
node version: v12.13.1
os: MacOS
typescript: 3.9.6
tslog: 2.6.1

I have no issue running this with `ts-node`, but when I actually run the tsc on my project and do a `node ./dist/index.js` I get the following error. I have tried removing it and everything works as expected, but as soon as I even just instantiate the `new Logger()` I get the error below. 

```
/Users/****/source/*****/node_modules/@babel/template/lib/builder.js:71
      rootStack = error.stack.split("\n").slice(3).join("\n");
```

tsconfig.json

```{
  "compilerOptions": {
    "target": "es5",
    "lib": ["esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": false,
    "strict": true,
    "noErrorTruncation": true,
    "rootDir": "src",
    "outDir": "dist",
    "sourceMap": true
  },
  "include": ["./src/**/*"],
  "exclude": [
    "node_modules"
  ]
}```

**Comment by terehov** [comment]
Thanks for reporting. 
Should be fixed in `2.6.2`.

**Comment by DevFlex** [comment]
@terehov I have upgraded to 2.6.2 and it is still throwing that same error. I will try to give a reproduction case when I get some time today.

**Comment by terehov** [comment]
That would be awesome, thx.

**Comment by DevFlex** [comment]
The more I look into it I am thinking this might not be an issue with tslog, but I figured I would post the reproduction case here let me know if there is anything else you need. The tsconfig I posted in the main issue. Thanks :)

index.ts

`import fetch from 'isomorphic-fetch';
import { Logger } from 'tslog';


import { print } from 'graphql';
import { makeRemoteExecutableSchema, stitchSchemas, introspectSchema, makeExecutableSchema } from 'graphql-tools';

import {AsyncExecutor} from "@graphql-tools/delegate";

const log = new Logger();

const executor = (uri: string) => {
  const asyncExecutor: AsyncExecutor = async ({ document, variables }) => {
    const query = print(document);
    const fetchResult = await fetch(uri, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query, variables })
    });
    return fetchResult.json();
  };
  return asyncExecutor;
};

log.info('reproduction case...');

async function getRemoteSchema({ uri }: { uri: string }) {
  const remoteExecutor = executor(uri);
  const schema = await introspectSchema(remoteExecutor);
  const executableSchema = makeRemoteExecutableSchema({ schema, executor: remoteExecutor });

  return executableSchema;
}`

package.json
`{
  "dependencies": {
    "apollo-link": "^1.2.14",
    "apollo-link-http": "^1.5.17",
    "apollo-server": "^2.15.1",
    "dotenv": "^8.2.0",
    "graphql": "^15.3.0",
    "graphql-tools": "^6.0.12",
    "isomorphic-fetch": "^2.2.1",
    "node-fetch": "^2.6.0",
    "tslog": "^2.6.2"
  },
  "scripts": {
    "compile": "yarn rimraf ./dist && tsc",
    "start": "yarn compile && node ./dist/index.js"
  },
  "devDependencies": {
    "@types/isomorphic-fetch": "^0.0.35",
    "@types/node": "^14.0.22",
    "@types/node-fetch": "^2.5.7",
    "rimraf": "^3.0.2",
    "tslint": "^6.1.2",
    "typescript": "^3.9.6"
  }
}
`

**Comment by terehov** [comment]
Thanks, I’ll try it out tomorrow morning.

**Comment by terehov** [comment]
Thank you. I guess @deman4ik gave me the right hint in #34. 

Can you please try `v2.6.3`? Thx.

**Comment by DevFlex** [comment]
@terehov v2.6.3 fixed it thanks :)
